# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 15:07
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0002_auto_20160921_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=10),
        ),
    ]
