# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0003_projet_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='designer',
            field=models.CharField(blank=True, default=False, max_length=255, null=True),
        ),
    ]
