# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0004_projet_designer'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetcaption',
            name='image_format',
            field=models.CharField(choices=[('square', 'square'), ('banner', 'banner')], default=False, max_length=50),
            preserve_default=False,
        ),
    ]
