# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0005_projetcaption_image_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projetcaption',
            name='description',
        ),
    ]
