# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0006_remove_projetcaption_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projetcaption',
            old_name='Projet',
            new_name='projet',
        ),
    ]
