# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 07:14
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0007_auto_20161018_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='illustration_alternative',
            field=mezzanine.core.fields.FileField(blank=True, max_length=255, verbose_name='Illustration alternative'),
        ),
    ]
